export let games = [{
	"id": 342180,
	"type": "射击游戏",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/342180/header.jpg",
	"title": "亚利桑那阳光",
	"context": "一款专为虚拟现实打造的游戏，将让你置身于僵尸横行的末日世界",
	"isWant": 0
}, {
	"id": 716400,
	"type": "动作游戏",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/716400/header.jpg",
	"title": "赤壁之战",
	"context": "扮演三国武将，过五关斩六将",
	"isWant": 0
}, {
	"id": 858260,
	"type": "动作游戏",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/858260/header.jpg",
	"title": "符文剑士",
	"context": "游戏过程中教你使用剑法防御和进攻",
	"isWant": 0
}, {
	"id": 528260,
	"type": "动作游戏",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/528260/header.jpg",
	"title": "巨人杀手",
	"context": "用剑盾，枪等武器杀死巨人小兵和BOSS",
	"isWant": 0
}, {
	"id": 520270,
	"type": "刺激游戏",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/520270/header.jpg",
	"title": "过山车",
	"context": "就是过山车",
	"isWant": 0
}, {
	"id": 486780,
	"type": "新手推荐",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/486780/header.jpg",
	"title": "水果忍者",
	"context": "VR切水果，3岁都能玩",
	"isWant": 0
}, {
	"id": 620980,
	"type": "新手推荐",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/620980/header.jpg",
	"title": "节奏光剑",
	"context": "没玩过节奏光剑等于没玩过VR",
	"isWant": 0
}, {
	"id": 1098100,
	"type": "新手推荐",
	"src": "https://media.st.dl.pinyuncloud.com/steam/apps/1098100/header.jpg",
	"title": "墙来了",
	"context": "站着干啥？还不赶紧躲",
	"isWant": 0
}, {
	"id": 546560,
	"type": "新手推荐",
	"src": "https://media.st.dl.eccdnx.com/steam/apps/546560/header.jpg",
	"title": "半条命：爱莉克斯",
	"context": "最强VR游戏",
	"isWant": 0
}, {
	"id": 0,
	"type": "游戏",
	"src": "",
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}, {
	"id": 0,
	"type": '游戏',
	"src": '',
	"title": '',
	"context": '',
	"isWant": 0
}]
